In [1]:
import pandas as pd
import numpy as np
import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [2]:
def GET_Recomendados(title,cosine_sim,numbers):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:numbers]
    movies_indices = [i[0]for i in sim_scores]
    json = movies['title_x'].iloc[movies_indices]
    json = json.index
    json = movies.iloc[json.values]
    json = json[['original_title','overview','vote_average','vote_count','generos']].to_json()
    return json
def GET_PorNota(Number,df):
    top = df.query('vote_count > 5000')
    top = top.sort_values(['vote_average'],ascending=False)
    top = top.iloc[:Number]
    json = top[['original_title','overview','vote_average','vote_count','generos']].to_json()
    return json
def GET_Por_Production(df,production_companies):
    lista_id = []
    for i in range(len(df.production_companies_to)):
        aux = movies.production_companies_to[i]
        res = list(eval(aux))
        for j in range(len(res)):
            if(res[j]['name'] == production_companies):
                lista_id.append(i)
    lista_id = list(set(lista_id))
    date = df.iloc[lista_id]
    json = date[['original_title','overview','vote_average','vote_count','generos']].to_json()
    return json,date

In [3]:
movies = pd.read_csv("DEMO.csv")

In [4]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['soup'])
cosine_sim = linear_kernel(tfidf_matrix,tfidf_matrix)
indices = pd.Series(movies.index,index=movies['title_x']).drop_duplicates()

In [5]:
movies

,Unnamed: 0,budget,homepage,id,original_language,original_title,overview,popularity,release_date,revenue,...,vote_count,title_y,soup,generos,crew_to,production_companies_to,keywords_to,production_countries_to,cast_to,spoken_languages_to
0,0,237000000,http://www.avatarmovie.com/,19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,2009-12-10,2787965087,...,11800,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'credit_id': '52fe48009251416c750aca23', 'de...","[{'name': 'Ingenious Film Partners', 'id': 289...","[{'id': 1463, 'name': 'culture clash'}, {'id':...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso..."
1,1,300000000,http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,2007-05-19,961000000,...,4500,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'iso_639_1': 'en', 'name': 'English'}]"
2,2,245000000,http://www.sonypictures.com/movies/spectre/,206647,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,2015-10-26,880674609,...,4466,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'iso_639_1': 'fr', 'name': 'Français'}, {'is..."
3,3,250000000,http://www.thedarkknightrises.com/,49026,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,2012-07-16,1084939099,...,9106,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'id': 849, 'name': 'dc comics'}, {'id': 853,...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'iso_639_1': 'en', 'name': 'English'}]"
4,4,260000000,http://movies.disney.com/john-carter,49529,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,2012-03-07,284139100,...,2124,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 5, 'character': 'John Carter', 'c...","[{'iso_639_1': 'en', 'name': 'English'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,NaN,9367,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,1992-09-04,2040920,...,238,El Mariachi,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'credit_id': '52fe44eec3a36847f80b280b', 'de...","[{'name': 'Columbia Pictures', 'id': 5}]","[{'id': 5616, 'name': 'united states–mexico ba...","[{'iso_3166_1': 'MX', 'name': 'Mexico'}, {'iso...","[{'cast_id': 1, 'character': 'El Mariachi', 'c...","[{'iso_639_1': 'es', 'name': 'Español'}]"
4799,4799,9000,NaN,72766,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,2011-12-26,0,...,5,Newlyweds,"[][{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749,...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'credit_id': '52fe487dc3a368484e0fb013', 'de...",[],[],[],"[{'cast_id': 1, 'character': 'Buzzy', 'credit_...",[]
4800,4800,0,http://www.hallmarkchannel.com/signedsealeddel...,231617,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,2013-10-13,0,...,6,"Signed, Sealed, Delivered","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...","[{'name': 'Front Street Pictures', 'id': 3958}...","[{'id': 248, 'name': 'date'}, {'id': 699, 'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 8, 'character': 'Oliver O’Toole',...","[{'iso_639_1': 'en', 'name': 'English'}]"
4801,4801,0,http://shanghaicalling.com/,126186,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,2012-05-03,0,...,7,Shanghai Calling,[][]When ambitious New York attorney Sam is se...,[],"[{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...",[],[],"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 3, 'character': 'Sam', 'credit_id...","[{'iso_639_1': 'en', 'name': 'English'}]"
4802,4802,0,NaN,25975,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,2005-08-05,0,...,16,My Date with Drew,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{'id': 99, 'name': 'Documentary'}]","[{'credit_id': '58ce021b9251415a390165d9', 'de...","[{'name': 'rusty bear entertainment', 'id': 87...","[{'id': 1523, 'name': 'obsession'}, {'id': 224...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'cast_id': 3, 'character': 'Herself', 'credi...","[{'iso_639_1': 'en', 'name': 'English'}]"